"""Standalone HTTP app and optional Hub app factory."""

from collections.abc import AsyncGenerator
from contextlib import asynccontextmanager
from importlib.metadata import version
from urllib.parse import urlsplit

from fastapi import FastAPI, WebSocket
from mcp.server.transport_security import TransportSecuritySettings

from chat2local.hub.router import DeviceRouter
from chat2local.hub.websocket import serve_device
from chat2local.mcp.server import create_mcp_server
from chat2local.mcp.tools import get_router
from chat2local.runtime.config import AuthConfig


def create_app(
    router: DeviceRouter | None = None, *, hub_token: str | None = None, auth: AuthConfig | None = None,
) -> FastAPI:
    if hub_token is not None and (not hub_token or router is None or router.registry is None):
        raise ValueError("Hub requires a token and a device registry")
    server = create_mcp_server(router, auth=auth)
    oauth_enabled = server.settings.auth is not None
    transport_security = None
    if oauth_enabled:
        public_url = urlsplit(str(server.settings.auth.resource_server_url))
        # Keep DNS rebinding checks, admitting only the configured public origin
        # in addition to the SDK's existing loopback development addresses.
        public_host = public_url.netloc
        public_origin = f"https://{public_host}"
        transport_security = TransportSecuritySettings(
            allowed_hosts=["127.0.0.1:*", "localhost:*", "[::1]:*", public_host],
            allowed_origins=["http://127.0.0.1:*", "http://localhost:*", "http://[::1]:*", public_origin],
        )
    # OAuth metadata routes generated by the SDK must live at the external root.
    # Preserve the original /mcp mount (including /mcp/ clients) in none mode.
    mcp_app = server.streamable_http_app(
        streamable_http_path="/mcp" if oauth_enabled else "/", json_response=True,
        transport_security=transport_security,
    )

    @asynccontextmanager
    async def lifespan(_: FastAPI) -> AsyncGenerator[None, None]:
        local_router = router if router is not None else get_router()
        async with server.session_manager.run():
            try:
                yield
            finally:
                try:
                    if local_router.registry is not None:
                        await local_router.registry.close()
                finally:
                    await local_router.local.process_manager.shutdown()

    application = FastAPI(title="Chat2Local", version=version("chat2local"), lifespan=lifespan)
    application.state.router = router
    application.state.mcp = server

    @application.get("/health")
    async def health() -> dict[str, str]:
        return {"status": "ok"}

    if hub_token is not None:
        @application.websocket("/device/ws")
        async def device_socket(websocket: WebSocket) -> None:
            await serve_device(websocket, router.registry, hub_token)

    application.mount("/" if oauth_enabled else "/mcp", mcp_app)
    return application


app = create_app()
